### ISSUE TITLE
Does not work on macOS Unity Editor

### ISSUE THREAD

**Issue by burakomer** [NullTale/ScriptableObjectCreator#1]
I have not been able to get this tool to work on macOS editor. Is this issue known? Whenever I click on the Scriptable Object option in the menu, the popup menu does not show.

Unity Editor 2021.3.21f1
macOS Sonoma 14.0

**Comment by burakomer** [comment]
Hello, bumping this with a new discovery. We discovered that it does not work on Windows in Unity 2022.3, our specific version is 2022.3.21f

I am hoping that this will be seen because this is a really good tool.

**Comment by NullTale** [comment]
Guys, somebody make a commit pls, it's section exists for you to support the tool existence and usability. The project is shared over two years for now, i see it's visited and downloaded almost every day, WTF!

@burakomer!!! you have a team to work with, say them they'll be fired if they don't fix these issue ARRRHGHGHG!!! (also they can  buy a mac too)

* btw it work fine on 2022.3.17f the text issue can be misleading
* macOS problems can be related to an issue from https://github.com/NullTale/LutLight2D/pull/1 with line sep

**Comment by burakomer** [comment]
@NullTale well, I fixed it myself today. It is not an exact fix, since I used EditorWindow.ShowModal instead of ShowPopup to show the PickerWindow. I specified it to only work that way if the Unity Editor is in macOS.

Would you like me to do a pull request?

**Comment by NullTale** [comment]
Ofc I like it!!! you'll be in contributors to
* but it must be platform specifiс to not break something (if I understand correctly, it's already there)
